services:

  backend:
    build: ./app/backend
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v3.5.1
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:main
    ports:
      - "3000:3000"